name: CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: docker.io
      NAMESPACE: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push ProductService
        run: |
          docker build -t $REGISTRY/$NAMESPACE/productservice:latest ./ProductService
          docker push $REGISTRY/$NAMESPACE/productservice:latest

      - name: Build & Push OrderService
        run: |
          docker build -t $REGISTRY/$NAMESPACE/orderservice:latest ./OrderService
          docker push $REGISTRY/$NAMESPACE/orderservice:latest

      - name: Build & Push ApiGateway
        run: |
          docker build -t $REGISTRY/$NAMESPACE/apigateway:latest ./ApiGateway
          docker push $REGISTRY/$NAMESPACE/apigateway:latest

    deploy:
    needs: build-and-push
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v4

      - name: Pull & Deploy with Docker Compose
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          cd $env:GITHUB_WORKSPACE
          docker-compose pull
          docker-compose up -d

