name: CI/CD - Distributed Microservices

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: self-hosted

    # Force toutes les commandes à s'exécuter sous PowerShell
    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 7 SDK (only on Linux runners)
        if: runner.os != 'Windows'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: |
          # Désactive la policy PowerShell pour cette session
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          dotnet restore

      - name: Build solution
        run: dotnet build --no-restore

      - name: Run tests (if any)
        run: dotnet test --no-build --verbosity normal

      - name: Docker Compose up (build all)
        run: docker-compose up --build -d

      - name: Check services are up
        run: docker ps
