name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ ApiGateway, ProductService, OrderService ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 7 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore & Build ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release

      - name: (Optional) Run tests in ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: |
          if [ -d "tests" ]; then
            dotnet test --no-build --verbosity normal
          else
            echo "No tests for this service"
          fi
